//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyManagementBusinessLayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CMBusinessResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CMBusinessResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CompanyManagementBusinessLayer.CMBusinessResources", typeof(CMBusinessResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An already started project cannot be deleted..
        /// </summary>
        internal static string AlreadyStartedProjectNotDeletedErrorMessage {
            get {
                return ResourceManager.GetString("AlreadyStartedProjectNotDeletedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An already started task cannot be deleted.
        /// </summary>
        internal static string AlreadyStartedTaskNotDeletedErrorMessage {
            get {
                return ResourceManager.GetString("AlreadyStartedTaskNotDeletedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete technology used in more than {0} projects..
        /// </summary>
        internal static string DeleteTechnologyErrorMessage {
            get {
                return ResourceManager.GetString("DeleteTechnologyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string MaxNumberOfProjects {
            get {
                return ResourceManager.GetString("MaxNumberOfProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string MaxNumberOfProjectsEmployee {
            get {
                return ResourceManager.GetString("MaxNumberOfProjectsEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot assign more than {0} projects to an Employee..
        /// </summary>
        internal static string MaxNumberOfProjectsEmployeeErrorMessage {
            get {
                return ResourceManager.GetString("MaxNumberOfProjectsEmployeeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string MaxNumberOfProjectsPM {
            get {
                return ResourceManager.GetString("MaxNumberOfProjectsPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot assign more than {0} projects to an PM..
        /// </summary>
        internal static string MaxNumberOfProjectsPMErrorMessage {
            get {
                return ResourceManager.GetString("MaxNumberOfProjectsPMErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string MaxNumberOfTechnologies {
            get {
                return ResourceManager.GetString("MaxNumberOfTechnologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot assign more than {0} technologies to a task..
        /// </summary>
        internal static string MaxNumberOfTechnologiesErrorMessage {
            get {
                return ResourceManager.GetString("MaxNumberOfTechnologiesErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology is not assigned in project..
        /// </summary>
        internal static string TechnologyNotAssignedErrorMessage {
            get {
                return ResourceManager.GetString("TechnologyNotAssignedErrorMessage", resourceCulture);
            }
        }
    }
}
