//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyManagementDataLayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CMResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CMResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CompanyManagementDataLayer.CMResources", typeof(CMResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address ID is missing..
        /// </summary>
        internal static string AddressIDMissing {
            get {
                return ResourceManager.GetString("AddressIDMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Fields Present..
        /// </summary>
        internal static string AllFieldsPresent {
            get {
                return ResourceManager.GetString("AllFieldsPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID is missing..
        /// </summary>
        internal static string ClientIDMissing {
            get {
                return ResourceManager.GetString("ClientIDMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department ID is missing..
        /// </summary>
        internal static string DepartmentIDMissing {
            get {
                return ResourceManager.GetString("DepartmentIDMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation ID is missing..
        /// </summary>
        internal static string DesignationIDMissing {
            get {
                return ResourceManager.GetString("DesignationIDMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Already Assigned for this Project..
        /// </summary>
        internal static string EmployeeAlreadyExistProject {
            get {
                return ResourceManager.GetString("EmployeeAlreadyExistProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID is missing..
        /// </summary>
        internal static string EmployeeIDMissing {
            get {
                return ResourceManager.GetString("EmployeeIDMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID is not exist..
        /// </summary>
        internal static string EmployeeIDNotExist {
            get {
                return ResourceManager.GetString("EmployeeIDNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is missing..
        /// </summary>
        internal static string FirstNameMissing {
            get {
                return ResourceManager.GetString("FirstNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Date is missing..
        /// </summary>
        internal static string JoinDateMissing {
            get {
                return ResourceManager.GetString("JoinDateMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is missing..
        /// </summary>
        internal static string LastNameMissing {
            get {
                return ResourceManager.GetString("LastNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project ID is missing..
        /// </summary>
        internal static string ProjectIDMissing {
            get {
                return ResourceManager.GetString("ProjectIDMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project ID is not exist..
        /// </summary>
        internal static string ProjectIDNotExist {
            get {
                return ResourceManager.GetString("ProjectIDNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name is missing..
        /// </summary>
        internal static string ProjectNameMissing {
            get {
                return ResourceManager.GetString("ProjectNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status ID is missing..
        /// </summary>
        internal static string StatusIDMissing {
            get {
                return ResourceManager.GetString("StatusIDMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Name is Missing..
        /// </summary>
        internal static string TaskNameMissing {
            get {
                return ResourceManager.GetString("TaskNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology ID is not exist..
        /// </summary>
        internal static string TechnologyIDNotExist {
            get {
                return ResourceManager.GetString("TechnologyIDNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technoloy Name is missing..
        /// </summary>
        internal static string TechnologyNameMissing {
            get {
                return ResourceManager.GetString("TechnologyNameMissing", resourceCulture);
            }
        }
    }
}
